01_top_pageのUIを組む。
shinonome-inc/mobile_Koshi pull request #1
Opened 2021-07-18 07:06 UTC by Yoshida-koshi

2021-07-18 07:09 UTC, Yoshida-koshi commented
01_top_pageのUIを組み終えたのでレビューお願いします。https://github.com/shinonome-inc/mobile_Koshi/pull/1/commits/dc999fb71ce73ad725447ac469a71a7be6cfe6f9

2021-07-18 08:57 UTC, mcz9mm requested changes
修正お願いします。

レイアウトに関しては動画や[こちらの記事](https://medium.com/flutter-community/flutter-layout-cheat-sheet-5363348d037e)を参考にしてください。

2021-07-18 08:57 UTC, mcz9mm commented on lib/01_top_page.dart
> +void main() {
`main.dart`にmain()があるので不要です

2021-07-18 08:57 UTC, mcz9mm commented on lib/01_top_page.dart
> +class MyApp extends StatelessWidget {
MyApp classではなく`top_page.dart`でTopPage classを作成してください。
また、ファイル名は番号のPrefixは不要です

2021-07-18 08:57 UTC, mcz9mm commented on lib/01_top_page.dart
> +class MyApp extends StatelessWidget {
というかそもそもこの状態だとmain.dartの方のMyAppが起動されるよ

2021-07-18 08:57 UTC, mcz9mm commented on lib/01_top_page.dart
> +                image: AssetImage('images/background.png'),
git上で`background `が追加されていないため、私の方で参照できていないです
ファイルの追加もaddしてください
<img width="212" alt="スクリーンショット 2021-07-18 17 44 09" src="https://user-images.githubusercontent.com/11751495/126061269-1a539f4e-10be-4089-9db0-d541c9edd659.png">

2021-07-18 08:57 UTC, mcz9mm commented on lib/01_top_page.dart
> +                  fontFamily: 'Pacifico',
これ自分の方でFontが反映されていないですが、正しく表示されていますか？
Fontを追加した場合、`pubspec.yaml`に記載しないと使えないはずです。

2021-07-18 08:57 UTC, mcz9mm commented on lib/01_top_page.dart
> +                padding: EdgeInsets.fromLTRB(45, 0, 0, 319),
Paddingはパーツ間のサイズを調整するくらいで、絶対値でBottom指定で319とかにすると
iPadなどの大きいサイズでズレが生じます。
Expandedなどを使って解決してみてください

https://www.youtube.com/watch?v=nbp3U5tci6U&list=PLysb2bLUBFH0pZ1XWz8kEP45JX9g_spOe&index=21

<img width="851" alt="スクリーンショット 2021-07-18 17 50 02" src="https://user-images.githubusercontent.com/11751495/126061429-cb2c87be-b1ed-41a3-a5d4-3e20aa041cd2.png">

2021-07-18 08:58 UTC, mcz9mm commented on lib/01_top_page.dart
> +          mainAxisAlignment: MainAxisAlignment.end,
start基準にして上からレイアウトを組むことをお勧めします

2021-07-18 09:11 UTC, mcz9mm commented on lib/01_top_page.dart
> +              image: new DecorationImage(
`new`は現在のFlutterのバージョンでは不要です

2021-07-18 09:11 UTC, mcz9mm commented on lib/01_top_page.dart
> +        floatingActionButton: Column(
`floatingActionButton`の使い方がよくないと思います。
https://api.flutter.dev/flutter/material/FloatingActionButton-class.html

bodyの背景の上にパーツを配置したいならStackなどを使って実装してみましょう。

https://androidride.com/flutter-background-image/

2021-07-18 09:20 UTC, mcz9mm commented on lib/01_top_page.dart
> +                child: ElevatedButton(
デザインが違うので、Figmaの通りに実装してみましょう。

<img width="510" alt="スクリーンショット 2021-07-18 18 18 47" src="https://user-images.githubusercontent.com/11751495/126062068-60168940-ac14-43d6-bf89-83ad26dc3a39.png">

2021-07-18 09:46 UTC, mcz9mm commented on lib/01_top_page.dart
> +              child: SizedBox(
SizedBoxは不要かな

2021-07-18 09:58 UTC, mcz9mm commented
最初なので実装例を書いておきます
StackとExpandedを使った実装です。

中身のWidgetは適宜置き換えてください。

<img width="636" alt="スクリーンショット 2021-07-18 18 53 24" src="https://user-images.githubusercontent.com/11751495/126062883-030b518e-2293-4a78-898c-9d9dc09fc92c.png">

```
    return MaterialApp(
      home: Scaffold(
        body: Stack(
          children: [
            Container(
              decoration: BoxDecoration(
                  image: DecorationImage(
                    colorFilter: ColorFilter.mode(
                        Colors.black.withOpacity(0.2),
                        BlendMode.luminosity),
                    image: AssetImage('images/background.png'),
                    fit: BoxFit.cover,
                  )
              ),
            ),
            Column(
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
                Expanded(flex: 3, child: Container(color: Colors.grey.withAlpha(150),)),
                Container(
                  child: Text("Qiita Feed app",
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 36,
                      fontFamily: 'Pacifico',
                    ),
                  ),
                ),
                Container(
                  padding: EdgeInsets.symmetric(vertical: 8),
                  child: Text("-playground-",
                    style: TextStyle(
                      fontSize: 14,
                      color: Colors.white,
                    ),
                  ),
                ),
                Expanded(flex: 5, child: Container(color: Colors.grey.withAlpha(150),)),
                SizedBox(
                  height: 50,
                  width: 360,
                  child: Container(color: Colors.blueAccent,),
                ),
                Container(
                  margin: EdgeInsets.only(bottom: 40),
                  height: 50,
                  width: 360,
                  color: Colors.red,
                ),
              ],
            ),
          ],
        ),
      ),
    );
```

2021-07-19 01:59 UTC, Yoshida-koshi commented on lib/01_top_page.dart
> +                image: AssetImage('images/background.png'),
pubspec.yamlを追加するの忘れていたので追加しました。
edeb5f2

2021-07-19 01:59 UTC, Yoshida-koshi commented on lib/01_top_page.dart
> +                  fontFamily: 'Pacifico',
pubspec.yaml追加するの忘れていたので追加しました。
edeb5f2

2021-07-23 03:49 UTC, Yoshida-koshi commented
上の実装例をもとに修正したのでレビューをお願いします。https://github.com/shinonome-inc/mobile_Koshi/pull/1/commits/10a6162a8eb0fe6c4010fdc767253e0884844214

2021-07-23 04:06 UTC, Yoshida-koshi commented
上の実装例をもとに修正したのでレビューをお願いします。https://github.com/shinonome-inc/mobile_Koshi/pull/1/commits/64c8d5f494f98f776f400fc426a6457e18c82fb9

2021-07-23 04:16 UTC, mcz9mm commented on lib/01_top_page.dart
> +void main() {
MUST：修正お願いします。
`main.dart`側の方を修正しないと初期状態のアプリの方が起動されます。

```
void main() {
  runApp(TopPage());
}
```

<img width="626" alt="スクリーンショット 2021-07-23 13 14 26" src="https://user-images.githubusercontent.com/11751495/126736655-55195157-3adb-4c8d-a61d-f5343c24c8cc.png">

2021-07-23 04:16 UTC, mcz9mm commented on lib/01_top_page.dart
> +class MyApp extends StatelessWidget {
ファイル名の修正をお願いします。

2021-07-23 04:21 UTC, mcz9mm requested changes
修正お願いします。
1. ファイル名の修正 `01._top_page.dart`→`top_page.dart`
2. `TopPage`側の`main()`の削除、`main.dart`側の`main()`でTopPageを呼び出すこと

2021-07-23 04:22 UTC, mcz9mm commented on lib/01_top_page.dart
> +                image: AssetImage('images/background.png'),
OK

2021-07-23 04:22 UTC, mcz9mm commented on lib/01_top_page.dart
> +                  fontFamily: 'Pacifico',
OK

2021-07-23 04:41 UTC, Yoshida-koshi commented
修正しました。
122e352　
6024f69

2021-07-28 09:54 UTC, mcz9mm requested changes
2点だけ修正したらOKです👍

2021-07-28 09:54 UTC, mcz9mm commented on lib/main.dart
> +      initialRoute: '/first',
細かいんだけど画面名と対応させた方がわかりやすいよ
`/first`→`/top`

2021-07-28 09:54 UTC, mcz9mm commented on lib/main.dart
>        theme: ThemeData(
あとは生成時の不要なコードは削除してしまいましょう

```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      initialRoute: '/first',
      routes: {
        '/first': (context) => TopPage(),
      },
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
    );
  }
}
```

2021-07-29 07:06 UTC, Yoshida-koshi commented
修正しました。レビューお願いします。https://github.com/shinonome-inc/mobile_Koshi/pull/1/commits/e805cb71aeba604194e5bf64c57c378b15ecfd55

2021-07-29 07:37 UTC, merged

2021-07-29 07:37 UTC, mcz9mm commented
LGTM