FolloweesPage：UIの実装完了
shinonome-inc/mobile_Koshi pull request #19
Opened 2022-01-25 08:32 UTC by Yoshida-koshi

2022-01-25 10:22 UTC, mcz9mm requested changes
エラー出てるかも
<img width="400" alt="スクリーンショット 2022-01-25 19 21 26" src="https://user-images.githubusercontent.com/11751495/150958760-9090600a-b600-49b1-b3a2-18d35bf6579b.png">


```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Center widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  Center ← Expanded ← FutureBuilder<List<User>> ← Center ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← ⋯
When the exception was thrown, this was the stack: 
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5723:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5739:6)
#2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5761:7)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5440:5)
#4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6082:11)
...
====================================================================================================
I/flutter (25202): [{"description":"","facebook_id":"","followees_count":23,"followers_count":13,"github_login_name":null,"id":"taitai9847","items_count":11,"linkedin_id":"","location":"","name":"taiyo ishikawa","organization":"","permanent_id":256549,"profile_image_url":"https://s3-ap-northeast-1.amazonaws.com/qiita-image-store/0/256549/f3456282132f060caa07320f0ff34f98f6f80838/large.png?1590768060","team_only":false,"twitter_screen_name":"taiyo_sw_bump","website_url":""},{"description":"Co-founder\u0026CTO of Shinonome, inc.","facebook_id":"hiroyoshi.takahashi.75","followees_count":66,"followers_count":65,"github_login_name":null,"id":"t-hiroyoshi","items_count":28,"linkedin_id":"","location":"Tokyo, Japan","name":"Hiroyoshi Takahashi","organization":"Shinonome, inc.","permanent_id":72314,"profile_image_url":"https://qiita-image-store.s3.amazonaws.com/0/72314/profile-images/1553063043","team_only":false,"twitter_screen_name":"t_hiroyoshi","website_url":"https://t-hiroyoshi.github.io"},{"description":"iOSエンジニアです�

======== Exception caught by widgets library =======================================================
The following _CastError was thrown building:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _FolloweesListState.build.<anonymous closure> (package:mobile_qiita_application/followees_list.dart:80:62)
#1      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:455:22)
#2      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1213:28)
#3      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1226:55)
#4      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2535:19)
...
====================================================================================================
```

2022-01-25 10:22 UTC, mcz9mm commented on lib/follows_page.dart
> +            if (snapshot.connectionState == ConnectionState.waiting) {
waiting👍

2022-01-25 10:26 UTC, mcz9mm commented
これも一緒に治してほしいところなんだけどマイページの上部はスクロールさせないようにしたいな

<img width="500" alt="スクリーンショット 2022-01-25 19 20 49" src="https://user-images.githubusercontent.com/11751495/150958836-76b156dd-53ce-42c2-9aff-7310b29134c8.png">

各パーツの余白もFigmaを見てそれ通りに調整してもらえると！

<img width="468" alt="スクリーンショット 2022-01-25 19 26 42" src="https://user-images.githubusercontent.com/11751495/150959507-77086263-6928-4ee5-96e7-539b0816933a.png">

2022-01-25 10:28 UTC, mcz9mm commented
ユーザー名が取得できない場合（テキストが空とか）、ユーザーIDを表示するようにしよう
@mcz9mm のばあいユーザー名が取得できない場合は`mcz9mm`と表記

2022-01-26 09:29 UTC, Yoshida-koshi commented
修正しました！
c3d4f4c

2022-01-26 10:06 UTC, mcz9mm commented
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Center widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  Center ← Expanded ← FutureBuilder<User> ← Center ← Column ← _SingleChildViewport ← IgnorePointer-[GlobalKey#751fb] ← Semantics ← Listener ← _GestureSemantics ← ⋯
When the exception was thrown, this was the stack: 
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5723:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5739:6)
#2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5761:7)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5440:5)
#4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6082:11)
...
====================================================================================================
```

2022-01-26 10:22 UTC, mcz9mm commented
ログイン時のUI部分で`SingleChildScrollView`を使う場合は必ず高さがきまった状態でないといけないです。Expandedは基本使えないはず。Columnで分けて、スクロール部分を下の記事のみにすればいい感じに表示されるはずです。

ユーザー情報部分の高さは`ConstrainedBox`などでサイズの上限を設けるとよさそうかな。
https://nzigen.com/reference/flutter/2018-05-01-constrained-box/

```
  Widget loginUI() {
    return Column(
      children: [
        ConstrainedBox(
          constraints: BoxConstraints(maxHeight: 256.0),
          child: FutureBuilder<User>(
            future: QiitaRepository.fetchAuthenticatedUser(),
            builder: (BuildContext context, AsyncSnapshot<User> snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return Expanded(
                  child: Center(
                    child: CircularProgressIndicator(),
                  ),
                );
              } else if (snapshot.hasError) {
                return ErrorPage(refreshFunction: () {
                  QiitaRepository.fetchAuthenticatedUser();
                });
              } else {
                return MyPageUserDetail(userData: snapshot.data);
              }
            },
          ),
        ),
        Row(
          children: [
            Expanded(
              child: Container(
                height: 28,
                decoration: BoxDecoration(
                  color: Constants.grey6,
                ),
                child: Container(
                  padding: EdgeInsets.only(left: 16, top: 4, bottom: 8),
                  child: Text(
                    '投稿記事',
                    style: TextStyle(
                      fontSize: 12,
                      color: Constants.grey,
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
        Expanded(
          child: FutureBuilder<List<Item>>(
            future: QiitaRepository.fetchAuthenticatedUserItem(),
            builder:
                (BuildContext context, AsyncSnapshot<List<Item>> snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return Expanded(
                  child: Center(
                    child: CircularProgressIndicator(),
                  ),
                );
              } else if (snapshot.hasError) {
                return ErrorPage(
                  refreshFunction: () {
                    QiitaRepository.fetchAuthenticatedUserItem();
                  },
                );
              } else {
                return MyPageItemList(itemData: snapshot.data!);
              }
            },
          ),
        )
      ],
    );
  }
```


`MyPageUserDetail`の改善案

- 余白は左右を考慮でつけること。leftのみではなくrightの部分も意識してください。(テキスト量に応じて伸びるため）
- `24`→`16`ptに変更してください
- 全体をPaddingで覆うことでそれぞれのWidgetにmarginをつける必要がなくなるのでそのように修正しよう

```
 return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          CircleAvatar(
            backgroundImage: NetworkImage(widget.userData!.profileImageUrl),
            radius: 43,
          ),
          SizedBox(height: 16),
          Text(
            widget.userData!.name.isNotEmpty
                ? widget.userData!.name
                : widget.userData!.id,
            style: TextStyle(
              fontSize: 14,
              letterSpacing: 0.25,
              color: Constants.black,
            ),
          ),
          SizedBox(height: 4),
          Text(
            '@${widget.userData!.id}',
            style: TextStyle(
              fontSize: 12,
              letterSpacing: 0.25,
              color: Constants.grey,
            ),
          ),
          SizedBox(height: 16),
          Text(
            widget.userData!.description != null
                ? widget.userData!.description!
                : "",
            style: TextStyle(
              fontSize: 12,
              letterSpacing: 0.25,
              color: Constants.grey,
            ),
          ),
          SizedBox(height: 16),
          Row(
            children: [
              Builder(
                builder: (context) => InkWell(
                  onTap: () {
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (_) =>
                                FollowsPage(userData: widget.userData!)));
                  },
                  child: Text(
                    '${widget.userData!.followeesCount}',
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w700,
                      color: Constants.black,
                    ),
                  ),
                ),
              ),
              SizedBox(width: 5),
              Text(
                'フォロー中',
                style: TextStyle(
                  fontSize: 12,
                  color: Constants.grey,
                ),
              ),
              SizedBox(width: 8),
              Builder(
                builder: (context) => InkWell(
                  onTap: () {
                    Navigator.push(context,
                        MaterialPageRoute(builder: (_) => FollowersPage()));
                  },
                  child: Text(
                    '${widget.userData!.followersCount}',
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w700,
                      color: Constants.black,
                    ),
                  ),
                ),
              ),
              SizedBox(width: 5),
              Text(
                'フォロワー',
                style: TextStyle(
                  fontSize: 12,
                  color: Constants.black,
                ),
              )
            ],
          )
        ],
      ),
    );
  }
```
<img width="547" alt="スクリーンショット 2022-01-26 19 16 33" src="https://user-images.githubusercontent.com/11751495/151145625-e0c539b9-2811-4dc3-998f-73c14edd8cb4.png">

2022-01-26 10:44 UTC, Yoshida-koshi commented
Kaoruさんの修正案をもとに修正しました！
40fc4d3

2022-01-26 10:48 UTC, merged