テストでの修正完了
shinonome-inc/mobile_Koshi pull request #26
Opened 2022-02-17 08:46 UTC by Yoshida-koshi

2022-02-17 12:03 UTC, mcz9mm requested changes
不用意にExpandedを使っている箇所が目立つので一度実装の見直しをしてみると良いかも

Expandedの挙動や使い方も復習してみてください
https://api.flutter.dev/flutter/widgets/Expanded-class.html

2022-02-17 12:03 UTC, mcz9mm commented on lib/follows_page.dart
> +            return Expanded(
Expandedの中にExpandedが入ってるのなんでだw
不要なので削除してください

2022-02-17 12:03 UTC, mcz9mm commented on lib/follows_page.dart
> +            return Expanded(
エラー出てます
```
The ownership chain for the RenderObject that received the parent data was:
  Center ← Expanded ← FutureBuilder<List<User>> ← Expanded ← FollowsPage ← Column ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← ⋯
When the exception was thrown, this was the stack: 
```

2022-02-17 12:03 UTC, mcz9mm commented on lib/follows_page.dart
> +            return Expanded(
FollowersPageも一緒なので修正お願いします

2022-02-18 00:32 UTC, Yoshida-koshi commented on lib/feed_page.dart
>  class _FeedPageState extends State<FeedPage> {
無限スクロールならlib/item_list.dart
で実装しています！

2022-02-18 01:38 UTC, Yoshida-koshi commented on lib/feed_page.dart
> +                    return Expanded(
修正しました！
[02df2af](https://github.com/shinonome-inc/mobile_Koshi/pull/26/commits/02df2afbfbc72ad114b1140b96b40cbe0f90afa1)

2022-02-18 01:38 UTC, Yoshida-koshi commented on lib/feed_page.dart
> +                      child: Center(
修正しました！
[02df2af](https://github.com/shinonome-inc/mobile_Koshi/pull/26/commits/02df2afbfbc72ad114b1140b96b40cbe0f90afa1)

2022-02-18 01:39 UTC, Yoshida-koshi commented on lib/feed_page.dart
> +                  try {
修正しました！
[02df2af](https://github.com/shinonome-inc/mobile_Koshi/pull/26/commits/02df2afbfbc72ad114b1140b96b40cbe0f90afa1)

2022-02-18 01:39 UTC, Yoshida-koshi commented on lib/feed_page.dart
> +                    if (snapshot.hasData) {
修正しました！
[02df2af](https://github.com/shinonome-inc/mobile_Koshi/pull/26/commits/02df2afbfbc72ad114b1140b96b40cbe0f90afa1)

2022-02-18 01:39 UTC, Yoshida-koshi commented on lib/follow_follower_page.dart
> +      body: Column(
修正しました！
[02df2af](https://github.com/shinonome-inc/mobile_Koshi/pull/26/commits/02df2afbfbc72ad114b1140b96b40cbe0f90afa1)

2022-02-18 01:39 UTC, Yoshida-koshi commented on lib/follow_follower_page.dart
> +          (() {
修正しました！
[02df2af](https://github.com/shinonome-inc/mobile_Koshi/pull/26/commits/02df2afbfbc72ad114b1140b96b40cbe0f90afa1)

2022-02-18 01:40 UTC, Yoshida-koshi commented on lib/follows_page.dart
> +            return Expanded(
修正しました！
[02df2af](https://github.com/shinonome-inc/mobile_Koshi/pull/26/commits/02df2afbfbc72ad114b1140b96b40cbe0f90afa1)

2022-02-18 05:24 UTC, merged

2022-02-18 05:24 UTC, mcz9mm commented on lib/feed_page.dart
>  class _FeedPageState extends State<FeedPage> {
iOSだと動かないんだよな〜
windowsだから検証しようがないのでまぁいいです