FeedPageのUI完成
shinonome-inc/mobile_Koshi pull request #5
Opened 2021-10-08 07:07 UTC by Yoshida-koshi

FeedPageのUIが完成したのでレビューをお願いします。
ちなみにログイン認証の部分をやっている時にUIは完成していたのでいらない所を削除しました。
9056151

2021-10-08 10:33 UTC, mcz9mm commented
ログインページのPRで伝えた通り、FeedPageについては中身レビューをしていないのでこちらに書きます。
他にもマイページやタグページも同様にUI修正の際に修正していきましょう。

### このPRで修正してほしい箇所
微妙にデザインと違うので修正お願いします

- [ ] 区切り線の位置をテキストに合わせてください
<img width="400" alt="スクリーンショット 2021-10-08 18 57 30" src="https://user-images.githubusercontent.com/11751495/136537103-4195d2c7-e2b7-44cd-b114-d76646418b5c.png">

- [ ] ユーザー名が長い場合だとはみ出る危険可能性があるので、タイトルと同様最大2行にしてください
<img width="400" alt="スクリーンショット 2021-10-08 19 03 31" src="https://user-images.githubusercontent.com/11751495/136537947-9e9fc585-5bd3-4e3b-aa9e-1dbbf0266784.png">

- [ ] DividerのカラーをFigmaのデザイン通りにする  #B2B2B2
https://github.com/shinonome-inc/mobile_Koshi/blob/develop/feed_page_ui/lib/item_list.dart#L71

```
    Divider(
         height: 5,
         thickness: 0.5,
         color: Colors.grey[600],
    )
```

## 別途修正箇所
これは別途issueを作成して別ブランチで対応してください

### Feed画面残機能

- 追加ローディング
- 検索時のonChangeで毎回検索ロジックが走っている(enterか確定で検索させたい)
- 検索エラー時の再読み込み機能

### QiitaRepository

- グローバル変数を使わないようにしたい

グローバル変数は、一見どこからでも参照・編集でき非常に便利に思えるのですが、思わぬバグを引き起こす原因になります。
今回だと`TagId`と`onFieldSubmittedText`がそれにあたりますが、うまく関数の引数や状態管理(Provider)などを使って実装するようにしてください。
https://github.com/shinonome-inc/mobile_Koshi/blob/develop/feed_page_ui/lib/qiita_repository.dart#L14

### Login

- 不要な実装の削除(_isLoading使ってないよね)
https://github.com/shinonome-inc/mobile_Koshi/blob/develop/feed_page_ui/lib/login.dart#L18

2021-10-12 02:29 UTC, Yoshida-koshi commented
UI修正完了しました。レビューお願いします。
48bf596

2021-10-12 04:49 UTC, mcz9mm requested changes
確認お願いします

2021-10-12 04:49 UTC, mcz9mm commented on lib/item_list.dart
> +                          maxLines: 2),
これは長くなる際のテキストで試してみたかな？
`Row`の中でidの部分だけ最大行を設定しても投稿日やLGTMの部分が伸びてしまうので対策をしないといけないです。

<img width="402" alt="スクリーンショット 2021-10-12 13 45 31" src="https://user-images.githubusercontent.com/11751495/136892907-821c45db-b19a-408a-b99d-2d81f33fdc72.png">

2021-10-12 04:49 UTC, mcz9mm commented on lib/item_list.dart
> +                          maxLines: 2),
Rowでテキストを連結するより1つの文字にすればRowが不要になって可変になると思うよ。
(Rowをどうしても使いたいならFlexibleとか使うとできそう。)
```
subtitle: Text(
    '@${widget.items[index].user.id} 投稿日: $date LGTM: ${widget.items[index].likesCount}',
    maxLines: 2,
),
```
<img width="397" alt="スクリーンショット 2021-10-12 13 48 50" src="https://user-images.githubusercontent.com/11751495/136893210-9cf883b1-7056-46b8-98e1-49cdc99e2e46.png">

2021-10-12 04:50 UTC, mcz9mm commented on lib/item_list.dart
> +                      child: Divider(
Dividerに`indent`引数があるのでそれで設定してください
```
indent: 72,
```

2021-10-12 04:50 UTC, mcz9mm commented on lib/item_list.dart
> +                      child: Divider(
そうするとPaddingが不要になります

2021-10-12 09:48 UTC, Yoshida-koshi commented on lib/item_list.dart
> +                          maxLines: 2),
修正完了しました。
e058465

2021-10-12 09:48 UTC, Yoshida-koshi commented on lib/item_list.dart
> +                      child: Divider(
修正完了しました。
e058465

2021-10-12 09:55 UTC, merged